### ISSUE TITLE
Search engine shows an error with specific request

### ISSUE THREAD

**Issue by jbpenrath** [openfun/richie#1395] opened 2021-06-28 07:55 UTC
## Bug Report

**Expected behavior/code**
Search engine should not shows an error when user applies a filter.

**Actual Behavior**

When user searches "Franco" then use the filter "Coming soon", search engine shows an error message "Something's wrong! Courses could not be loaded."
The bug does not occured with other request...

**Steps to Reproduce**
1. Go to the search page
2. Type `Franco`
3. Then select the filter `Coming soon`
4. The error message appears

**Environment**
- Richie version: 2.7.1
- Platform: Mac OS 11.4 - Firefox 89.0.2

**Additional context/Screenshots**
![2021-06-28 09 54 50](https://user-images.githubusercontent.com/9265241/123600424-f2c73400-d7f6-11eb-804c-0de373e22d7a.gif)

**Comment by sampaccoud** [comment] 2021-08-10 13:06
Closing as we could not reproduce this bug on any of our sites.

**Closed by sampaccoud** 2021-08-10 13:06 UTC
Labels: bug
